### PR TITLE
Support updating locked indirect dependencies

### PR DESCRIPTION
**Pull request by felixfbecker**
This adds support to update indirect dependencies in composer.lock that are not in composer.json. For new versions reported through https://github.com/dependencies-io/collector-php-composer/pull/12 that do not appear in composer.json, we require the latest compatible package version (which adds it to composer.json), then reset the composer.json back, leaving only the composer.lock updated.
Unfortunately `composer update package:version` [is not possible](https://github.com/composer/composer/issues/3387) but I tested that this works as a workaround.

### CODE REVIEW

**Comment by davegaeddert** [comment]
@felixfbecker I just realized we didn't get a test case added for this. Any chance you could add one?

**Comment by felixfbecker** [comment]
I don't know how the tests work - is there any documentation about that?

**Comment by davegaeddert** [comment]
Unfortunately no, but there are several examples in this repo.

It's an end-to-end test of sorts. So you need a directory with the composer.json and composer.lock as they would be before the dependency is updated. And then a copy of that directory with the changes made just like the actor would do.
```
tests/transitive/repo <- put the pre-update composer.json and composer.lock in here
tests/transitive/repo_final <- put the post-update files here (only composer.lock should have changes)
```

And you can put something like this in `tests/transitive/dependencies.json` to tell it what update to make:
```json
{
    "dependencies": [
        {
            "name": "<composer package name>",
            "source": "packagist",
            "path": "/",
            "installed": {
                "version": "<version that was installed originally>"
            },
            "available": [
                {
                    "version": "<the version that will be installed>"
                }
            ]
        }
    ]
}
```

And then a test case in `dependencies_tests.yml` to pull it all together:
```yml
- name: Transitive dependency test
  dockerfile: Dockerfile
  repo_contents: tests/transitive/repo
  dependencies_json: tests/transitive/dependencies.json
  tests:
    - |
        git checkout monolog/monolog-dev-master#7b99283-#0.0.0 && \
        diff -x '.git' ${CWD}/tests/transitive/repo_final/ ./
```

Let me know you have any questions or if that doesn't seem doable.

**Comment by davegaeddert** [comment]
There is actually a little bit of documentation, but not enough yet: https://www.dependencies.io/docs/build/cli/testing/

**Pull request merged**
